from utils.llm_client import call_llm

def buyer_pitch_agent(
    trend_output,
    product_concept,
    supplier_results,
    landed_cost_output,
    compliance_output,
    quality_output
):
    """
    Creates a buyer-facing pitch summary from all agent outputs.
    Prototype V1 uses structured rule-based generation.
    """

    product_name = product_concept["product_name"]
    retailer = product_concept["retailer"]
    season = product_concept["season"]
    category = product_concept["category"]
    trend_name = trend_output["trend_name"]

    top_supplier = supplier_results[0] if supplier_results else None

    if top_supplier:
        supplier_summary = (
            f"Recommended supplier: {top_supplier['supplier_name']} in "
            f"{top_supplier['country']} with a match score of "
            f"{top_supplier['match_score']}/100."
        )
    else:
        supplier_summary = (
            "No supplier has been finalized yet. Supplier validation is recommended "
            "before moving to sampling."
        )

    pitch_headline = f"{product_name} for {retailer} — {season}"

    executive_summary = (
        f"{product_name} is a trend-led {category.lower()} concept designed for "
        f"{retailer}'s {season} assortment. It is built around the "
        f"'{trend_name}' trend direction, combining accessible pricing, strong "
        f"visual appeal, and supplier-ready execution."
    )

    buyer_value = (
        f"This concept gives {retailer} a high perceived-value product while staying "
        f"close to the target FOB of ${product_concept['target_fob']}. The design "
        f"direction uses {', '.join(product_concept['hero_colors'])}, "
        f"{product_concept['pattern_direction'][0]}, and "
        f"{product_concept['material_recommendation'][0]} to create a product that "
        f"feels trend-right but commercially safe."
    )

    commercial_summary = (
        f"Estimated landed cost is ${landed_cost_output['estimated_landed_cost']} "
        f"with a suggested wholesale price of "
        f"${landed_cost_output['suggested_wholesale_price']}. Estimated gross margin "
        f"is {landed_cost_output['gross_margin_percent']}%, with gross profit of "
        f"${landed_cost_output['gross_profit_per_unit']} per unit."
    )

    risk_summary = (
        f"Compliance risk is currently rated {compliance_output['risk_level']} "
        f"with a compliance score of {compliance_output['compliance_score']}/100. "
        f"QC risk is rated {quality_output['risk_level']} based on product category "
        f"and supplier quality profile."
    )

    next_steps = [
        "Confirm buyer interest in concept direction",
        "Request physical sample from top 1–2 suppliers",
        "Validate FOB quote, MOQ, lead time, and packaging cost",
        "Complete compliance checklist before bulk production",
        "Run pre-production sample approval",
        "Conduct final random inspection before shipment"
    ]

    pitch = {
        "pitch_headline": pitch_headline,
        "executive_summary": executive_summary,
        "buyer_value": buyer_value,
        "supplier_summary": supplier_summary,
        "commercial_summary": commercial_summary,
        "risk_summary": risk_summary,
        "next_steps": next_steps,
        "short_pitch": (
            f"{product_name} is a {season} {category.lower()} concept for {retailer}, "
            f"built around the {trend_name} trend. It offers strong shelf appeal, "
            f"estimated landed cost of ${landed_cost_output['estimated_landed_cost']}, "
            f"and a recommended supplier path for sampling."
        )
    }

    return pitch
def llm_buyer_pitch_agent(buyer_pitch_output):
    """
    Turns structured buyer pitch into a more polished buyer-facing message.
    Falls back if LLM is unavailable.
    """

    prompt = f"""
You are writing a concise buyer-facing pitch for a US discount retail home goods buyer.

Use this structured pitch:
{buyer_pitch_output}

Return markdown with these exact sections:

## Buyer-Facing Pitch
## Why This Product Works
## Commercial Rationale
## Risk Controls
## Next Step Recommendation

Tone: professional, confident, realistic.
Do not mention that this was generated by AI.
"""

    llm_output = call_llm(prompt)

    if llm_output is None:
        return {
            "llm_available": False,
            "enhanced_pitch_markdown": None
        }

    return {
        "llm_available": True,
        "enhanced_pitch_markdown": llm_output
    }